services:
  data:
    image: mariadb:latest
    container_name: data
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - tp3-net

  script:
    build:
      context: ./php
    container_name: script
    volumes:
      - ./app:/app
    networks:
      - tp3-net
    depends_on:
      - data

  http:
    image: nginx:alpine
    container_name: http
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tp3-net
    depends_on:
      - script

networks:
  tp3-net:
    driver: bridge
